name: DivineBadges
version: ${project.version}
main: dev.mqgy.divinebadges.DivineBadges
author: mqgy
api-version: '1.21'
description: A gym badge system for Cobblemon servers - player-run gyms with virtual badge awards.

commands:
  badges:
    description: Opens your badge achievement menu
    usage: /badges
  badge:
    description: Admin badge management
    usage: /badge <create|delete|list|give|revoke|setleader|removeleader>

permissions:
  divinebadges.admin:
    description: Access to all admin badge commands
    default: op
  divinebadges.leader:
    description: Allows a player to award badges for their assigned gym
    default: false
  divinebadges.badges:
    description: Allows a player to view their badge collection
    default: true